apiVersion: v1
kind: Service
metadata:
  name: webbok-service
  namespace: app
spec:
  selector:
    app: webbok
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30037
