{
 "title": "Reddit_Application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total reques count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ui_request_count{path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate request count 1m ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(ui_request_count{path=\"/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90 procentil reques responce time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ui_request_response_time_bucket{path=\"/\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total number of requests distributed over response time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ui_request_response_time_bucket{path=\"/\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}