pipeline {
    agent {
        label 'master'
    }

    tools {
        maven 'MAVEN3.5.0'
    }

    environment {
        DOCKER_HUB_USERNAME = "'${credentials('DockerHubCreds').username}'"
        DOCKER_HUB_PASSWORD = "'${credentials('DockerHubCreds').password}'"
    }

    stages {
        stage('Build') {
            steps {
                // Ваши шаги сборки
            }
            post {
                // Ваши действия после успешной сборки
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImageName = 'webbok'
                    def dockerfilePath = 'cicd/lesson12/Dockerfile'
                    def jarFilePath = "${env.WORKSPACE}/apps/webbooks/target/*.jar"
                    def imageTag = "v1.${env.BUILD_NUMBER}"

                    sh "cp $jarFilePath ."
                    sh "docker build -t ${dockerImageName}:${imageTag} -f ${dockerfilePath} ."
                    sh "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}"
                    sh "docker push ${dockerImageName}:${imageTag}"
                }
            }
        }

        // Добавьте остальные этапы вашего пайплайна

        stage('Clean Up') {
            steps {
                script {
                    def dockerImageName = 'webbok'
                    def imageTag = "v1.${env.BUILD_NUMBER}"
                    sh "docker rmi ${dockerImageName}:${imageTag}"
                }
            }
        }
    }
}
