pipeline {
    agent {
        label 'master'
    }

    tools {
        maven 'MAVEN3.5.0'
    }

    environment {
        IMAGE_TAG = "webbok:${env.BUILD_NUMBER}"
        DOCKER_HUB_REPO = "boozyinjun/webbok"
        DOCKER_HUB_CREDENTIALS_ID = "DockerHubCreds"
        K8S_FILES_PATH = "${env.WORKSPACE}/cicd/lesson12"
        GIT_CREDENTIALS_ID = 'github-http'
        GIT_REPO_URL = 'https://github.com/boozyinjun/webbok.git'
        K8S_CREDENTIALS_ID = 'k8s-service-account-token'
        K8S_SERVER_URL = 'https://10.128.0.31:6443'
        // Переменные для Telegram add
        TELEGRAM_BOT_TOKEN = credentials('telegram-bot-token')
        TELEGRAM_CHAT_ID = credentials('telegram-chat-id')
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: "${GIT_CREDENTIALS_ID}", url: "${GIT_REPO_URL}"
            }
        }

        stage('Lint and Test') {
            when { 
                changeRequest()
            }
            steps {
                // Ваши линтинг и тестирование шаги
                dir('apps/webbooks') {
                    sh 'mvn -DDB.url=jdbc:postgresql://158.160.127.224:5432/db_webboks test'
                }
            }
            post {
                success {
                    dir('apps/webbooks') {
                        junit '**/target/surefire-reports/TEST-*.xml'
                    }
                }
            }
        }

        stage('Build and Archive') {
            steps {
                dir('apps/webbooks') {
                    sh 'mvn -DDB.url=jdbc:postgresql://158.160.127.224:5432/db_webboks package'
                }
            }
            post {
                success {
                    dir('apps/webbooks') {
                        archiveArtifacts 'target/*.jar'
                    }
                }
            }
        }
