apiVersion: v1
kind: Service
metadata:
  name: webbok-service
spec:
  type: LoadBalancer  # Изменяем тип сервиса на LoadBalancer
  selector:
    app: webbok
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8080
