apiVersion: v1
kind: Service
metadata:
  name: webbok-service
spec:
  selector:
    app: webbok
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
