apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webbok
  namespace: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webbok
  template:
    metadata:
      labels:
        app: webbok
    spec:
      containers:
        - name: webbok-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
