- name: Ping hosts
  hosts: web
  gather_facts: false
  vars_files: 
    - '{{ creds_locations }}'

  tasks:
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:

    - name:
      debug:
        msg: '{{user}}:{{password}}'
    